spring:
  application:
    name: service-user
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
server:
  port: 9009

ribbon:
  eureka:
    enabled: true
